### ISSUE TITLE
脚手架上架失败

### ISSUE THREAD

**Issue by GavinZhuLei** [ant-design/scaffold-market#177]
Name: vue-mobile
Url: git://github.com/GavinZhuLei/vue-mobile.git
看错误日志如下
```bash
events.js:165
      throw er; // Unhandled 'error' event
      ^
YAMLException: can not read a block mapping entry; a multiline key may not be an implicit key in "/home/travis/build/ant-design/scaffold-market/scaffolds/dva-boot/index.yml" at line 21, column 1:
    # Table of Contents
    ^
    at generateError (/home/travis/build/ant-design/scaffold-market/node_modules/js-yaml/lib/js-yaml/loader.js:165:10)
    at throwError (/home/travis/build/ant-design/scaffold-market/node_modules/js-yaml/lib/js-yaml/loader.js:171:9)
    at readBlockMapping (/home/travis/build/ant-design/scaffold-market/node_modules/js-yaml/lib/js-yaml/loader.js:1046:9)
    at composeNode (/home/travis/build/ant-design/scaffold-market/node_modules/js-yaml/lib/js-yaml/loader.js:1332:12)
    at readDocument (/home/travis/build/ant-design/scaffold-market/node_modules/js-yaml/lib/js-yaml/loader.js:1492:3)
    at loadDocuments (/home/travis/build/ant-design/scaffold-market/node_modules/js-yaml/lib/js-yaml/loader.js:1548:5)
    at load (/home/travis/build/ant-design/scaffold-market/node_modules/js-yaml/lib/js-yaml/loader.js:1569:19)
    at Object.safeLoad (/home/travis/build/ant-design/scaffold-market/node_modules/js-yaml/lib/js-yaml/loader.js:1591:10)
    at yaml2json (/home/travis/build/ant-design/scaffold-market/node_modules/gulp-yaml/index.js:15:41)
    at DestroyableTransform._transform (/home/travis/build/ant-design/scaffold-market/node_modules/gulp-yaml/index.js:63:25)
Emitted 'error' event at:
    at DestroyableTransform.onerror (/home/travis/build/ant-design/scaffold-market/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:558:12)
    at DestroyableTransform.emit (events.js:180:13)
    at DestroyableTransform._transform (/home/travis/build/ant-design/scaffold-market/node_modules/gulp-yaml/index.js:67:14)
    at DestroyableTransform.Transform._read (/home/travis/build/ant-design/scaffold-market/node_modules/readable-stream/lib/_stream_transform.js:184:10)
    at DestroyableTransform.Transform._write (/home/travis/build/ant-design/scaffold-market/node_modules/readable-stream/lib/_stream_transform.js:172:83)
    at doWrite (/home/travis/build/ant-design/scaffold-market/node_modules/readable-stream/lib/_stream_writable.js:418:64)
    at writeOrBuffer (/home/travis/build/ant-design/scaffold-market/node_modules/readable-stream/lib/_stream_writable.js:407:5)
    at DestroyableTransform.Writable.write (/home/travis/build/ant-design/scaffold-market/node_modules/readable-stream/lib/_stream_writable.js:334:11)
    at write (/home/travis/build/ant-design/scaffold-market/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:623:24)
    at flow (/home/travis/build/ant-design/scaffold-market/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:632:7)
`

**Comment by goWrongWay** [comment]
是的 快来处理啊
